### ISSUE TITLE
Trying to compile script it doesnt work

### ISSUE THREAD

**Issue by Ilikesolartweaks** [Nekoraru22/Valorant-instalock#1]
![image](https://user-images.githubusercontent.com/110793882/186383982-1ec8fcbb-4b3b-4083-b61d-ab21238b22f8.png)
title

**Comment by Nekoraru22** [comment]
I need more info...
Have you installed the requirements?

**Comment by Nekoraru22** [comment]
Python doesn't need to be compiled, you can just run it but if you want the compiled version I will upload it

**Comment by Nekoraru22** [comment]
I compiled the program with [auto-py-to-exe](https://pypi.org/project/auto-py-to-exe/). Im uploading it

**Comment by Ilikesolartweaks** [comment]
Hi, yes i'm just an idiot and didn't install the requirements. I apologize for wasting your time
