### ISSUE TITLE
will there be an exe in the future?

### ISSUE THREAD

**Issue by Enxivity** [Nekoraru22/Valorant-instalock#2]
just asking cause idk how to compile it ;-;

**Comment by Nekoraru22** [comment]
Of course, this week I do it and upload it

**Comment by Nekoraru22** [comment]
Of course, this week I do it and upload it

**Comment by Enxivity** [comment]
ok thanks :)

**Comment by xxGalaxyRobotxx** [comment]
Where is the exe idk now how to set it up
