### ISSUE TITLE
Is it bannable?

### ISSUE THREAD

**Issue by L1ghtsh33p** [Nekoraru22/Valorant-instalock#5]
I dont wanna get Banned

**Comment by Nekoraru22** [comment]
https://www.reddit.com/r/VALORANT/comments/uul59i/are_macros_banned_from_valorant/

Macros are supposed to be bannable if they help you within the game, being a simple quick click I don't know if it would count as help, it's something you can do yourself. So... I don't know what to tell you, I used it for quite some time back in the day and never had any problems.
